# L. Louque
# 1/9/2023-1/11/2023
# spongebob

import turtle
import random

t = turtle.Turtle()

def drawBody():
  #Body
  t.color('yellow')
  t.up()
  t.setpos(-100,-150)
  t.down()
  t.begin_fill()
  for x in range(0,2):
    for x in range(0,5):
      t.forward(40)
      t.dot(random.randint(75,90))
    t.left(90)
    for x in range(0,6):
      t.forward(50)
      t.dot(random.randint(75,90))
    t.left(90)
  t.end_fill()
    #Left Leg
  t.up()
  t.setpos(-90,-230)
  t.down()
  t.begin_fill()
  for x in range(0,2):
    t.forward(20)
    t.right(90)
    t.forward(60)
    t.right(90)
  t.end_fill()
    #Right Leg
  t.up()
  t.setpos(70,-230)
  t.down()
  t.begin_fill()
  for x in range(0,2):
    t.forward(20)
    t.right(90)
    t.forward(60)
    t.right(90)
  t.end_fill()
    #Left Arm
  t.up()
  t.setpos(-140,-110)
  t.down()
  t.begin_fill()
  t.setpos(-230,-150)
  t.setpos(-220,-160)
  t.setpos(-140,-125)
  t.end_fill()
    #Right Arm
  t.up()
  t.setpos(140,-110)
  t.down()
  t.begin_fill()
  t.setpos(230,-150)
  t.setpos(220,-160)
  t.setpos(140,-125)
  t.end_fill()
def drawClothes():
  #Shirt
  t.color('gray')
  t.up()
  t.setpos(-140,-200)
  t.down()
  t.begin_fill()
  for x in range(0,2):
    t.forward(280)
    t.left(90)
    t.forward(100)
    t.left(90)
  t.color('white')
  t.end_fill()
    #Left Sleeve
  t.color('gray')
  t.up()
  t.setpos(-140,-100)
  t.down()
  t.begin_fill()
  t.setpos(-170,-120)
  t.setpos(-155,-145)
  t.setpos(-140,-135)
  t.color('white')
  t.end_fill()
    #Right Sleeve
  t.color('gray')
  t.up()
  t.setpos(140,-100)
  t.down()
  t.begin_fill()
  t.setpos(170,-120)
  t.setpos(155,-145)
  t.setpos(140,-135)
  t.color('white')
  t.end_fill()
  #Pants
  t.color('saddleBrown')
  t.up()
  t.setpos(-140,-200)
  t.down()
  t.begin_fill()
  for x in range(0,2):
    t.forward(280)
    t.left(90)
    t.forward(50)
    t.left(90)
  t.end_fill()
    #Left Leg
  t.up()
  t.setpos(-100,-200)
  t.down()
  t.begin_fill()
  for x in range(0,4):
    t.forward(50)
    t.right(90)
  t.end_fill()
    #Right Leg
  t.up()
  t.setpos(50,-200)
  t.down()
  t.begin_fill()
  for x in range(0,4):
    t.forward(50)
    t.right(90)
  t.end_fill()
  #Belt
  t.up()
  t.setpos(-130,-160)
  t.color('black')
  t.width(10)
  for x in range(0,7):
    t.down()
    t.forward(20)
    t.up()
    t.forward(20)
  #Collar
  t.width(1)
  t.up()
  t.color('gray')
  t.setpos(-45,-100)
  t.down()
  t.setpos(-30,-120)
  t.setpos(-15,-100)
  t.up()
  t.width(1)
  t.up()
  t.color('gray')
  t.setpos(45,-100)
  t.down()
  t.setpos(30,-120)
  t.setpos(15,-100)
  t.up()
  #Tie
  t.width(4)
  t.down()
  t.color('red')
  t.begin_fill()
  t.setpos(-15,-140)
  t.setpos(0,-170)
  t.setpos(15,-140)
  t.setpos(-15,-100)
  t.end_fill()
  t.width(1)
def drawEyes():
  #Eyelashes
    #Left
  t.width(5)
  t.up()
  t.color("black")
  t.setpos(-70,135)
  t.down()
  t.setpos(-80,160)
  t.up()
  t.color("black")
  t.setpos(-50,135)
  t.down()
  t.setpos(-50,170)
  t.up()
  t.color("black")
  t.setpos(-30,135)
  t.down()
  t.setpos(-20,160)
    #Right
  t.width(5)
  t.up()
  t.color("black")
  t.setpos(70,135)
  t.down()
  t.setpos(80,160)
  t.up()
  t.color("black")
  t.setpos(50,135)
  t.down()
  t.setpos(50,170)
  t.up()
  t.color("black")
  t.setpos(30,135)
  t.down()
  t.setpos(20,160)
  #Whites
    #Left
  t.up()
  t.color('white')
  t.setpos(-50,75)
  t.down()
  t.begin_fill()
  t.circle(40)
  t.end_fill()
    #Right
  t.up()
  t.setpos(50,75)
  t.down()
  t.begin_fill()
  t.circle(40)
  t.end_fill()
  #Irises
    #Left
  t.up()
  t.color('darkCyan')
  t.setpos(-40,85)
  t.down()
  t.begin_fill()
  t.circle(25)
  t.end_fill()
    #Right
  t.up()
  t.setpos(40,85)
  t.down()
  t.begin_fill()
  t.circle(25)
  t.end_fill()
  #Pupils
    #Left
  t.up()
  t.color('black')
  t.setpos(-40,95)
  t.down()
  t.begin_fill()
  t.circle(15)
  t.end_fill()
    #Right
  t.up()
  t.setpos(40,95)
  t.down()
  t.begin_fill()
  t.circle(15)
  t.end_fill()
  #Sparkle
    #Left
  t.up()
  t.color('white')
  t.setpos(-50,115)
  t.down()
  t.begin_fill()
  t.circle(5)
  t.end_fill()
    #Right
  t.up()
  t.setpos(30,115)
  t.down()
  t.begin_fill()
  t.circle(5)
  t.end_fill()
def drawMouth():
    #Mouth
  t.up()
  t.color("maroon")
  t.setpos(50,10)
  t.down()
  t.begin_fill()
  t.setpos(-50,10)
  t.seth(270)
  t.circle(50,180)
  t.end_fill()
    #Tongue
  t.up()
  t.color("pink")
  t.setpos(25,-35)
  t.down()
  t.begin_fill()
  t.seth(90)
  t.circle(15,180)
  t.end_fill()
  t.up()
  t.color("pink")
  t.setpos(5,-35)
  t.down()
  t.begin_fill()
  t.seth(90)
  t.circle(15,180)
  t.end_fill()
  t.up()
  t.color("pink")
  t.down()
  t.begin_fill()
  t.seth(330)
  t.circle(50,60)
  t.end_fill()
    #Teeth
  t.color('gray')
  t.up()
  t.setpos(5,10)
  t.seth(0)
  t.width(1)
  t.down()
  t.begin_fill()
  for x in range(0,4):
    t.forward(20)
    t.right(90)
  t.color('white')
  t.end_fill()
  t.color('gray')
  t.up()
  t.setpos(-20,10)
  t.seth(0)
  t.down()
  t.begin_fill()
  for x in range(0,4):
    t.forward(20)
    t.right(90)
  t.color('white')
  t.end_fill()
def drawNose():
  t.up()
  t.begin_fill()
  t.setpos(-20,50)
  t.color("darkOrange")
  t.down()
  t.setpos(40,50)
  t.circle(-8,180)
  t.setpos(-20,34)
  t.color("yellow")
  t.end_fill()
t.ht()
t.speed(0)

drawBody()
drawClothes()
drawEyes()
drawMouth()
drawNose()